extraction:
  cpp:
    after_prepare: 
      - python report.py 112
  cobol:
    after_prepare: 
      - python report.py 112
  csharp:
    after_prepare: 
      - python report.py 112
  java:
    after_prepare: 
      - python report.py 112
  javascript:
    after_prepare: 
      - python report.py 112
  python:
    after_prepare: 
      - python report.py 112
